// Second half of `cargo test -p kt-types && pnpm -C shell/ui gen:types`.
//
// ts-rs writes one .ts per exported type into crates/kt-types/bindings/ when
// kt-types' tests run. This mirrors them into src/generated/ and writes a
// barrel so the UI imports from one place. CI regenerates and fails on a diff,
// so the checked-in output is always current (CLAUDE.md rule 8).
import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const BINDINGS = resolve(here, "../../../crates/kt-types/bindings");
const OUT = resolve(here, "../src/generated");

let sources;
try {
  sources = readdirSync(BINDINGS).filter((f) => f.endsWith(".ts")).sort();
} catch {
  console.error(
    `No bindings at ${BINDINGS}.\nRun 'cargo test -p kt-types' first - ts-rs writes them during the test run.`,
  );
  process.exit(1);
}

if (sources.length === 0) {
  console.error(`${BINDINGS} is empty. Does any type still carry #[ts(export)]?`);
  process.exit(1);
}

rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT, { recursive: true });

for (const file of sources) {
  writeFileSync(join(OUT, file), readFileSync(join(BINDINGS, file)));
}

const barrel = [
  "// Generated by scripts/gen-types.mjs from crates/kt-types. Do not edit.",
  "// Regenerate: cargo test -p kt-types && pnpm -C shell/ui gen:types",
  "",
  ...sources.map((f) => {
    const name = f.replace(/\.ts$/, "");
    return `export type { ${name} } from "./${name}";`;
  }),
  "",
].join("\n");

writeFileSync(join(OUT, "index.ts"), barrel);
console.log(`generated ${sources.length} types into src/generated/`);
